spring.application.name=pgms-backend
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pgms_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:pgms_user}
spring.datasource.password=${DB_PASSWORD:Pgms@1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=PGMSJwtSecretKeyForHs256SigningMustBeLongEnough1234567890
app.jwt.expiration-ms=86400000


# CREATE USER 'pgms_user'@'localhost' IDENTIFIED BY 'Pgms@1234';
# GRANT ALL PRIVILEGES ON pgms_db.* TO 'pgms_user'@'localhost';
# FLUSH PRIVILEGES;

# SELECT user, host FROM mysql.user;
